### ISSUE TITLE
Can Flask Fanstatic Render Versioned Images

### ISSUE THREAD

**Issue by schneems** [mgood/flask-fanstatic#1]
I need to render versioned images in my templates, i was asking how to do this on the fanstatic bitbucket repo, and someone mentioned that it was possible but dependent on the integration layer. Original question: https://bitbucket.org/fanstatic/fanstatic/issue/81/images-with-fanstatic. 

Does flask-fanstatic support template image rendering, and if so, can you help me with the syntax?

**Comment by mgood** [comment]
I think the code suggested for your original question should also work here.  Flask-Fanstatic provides some convenience APIs, but you can still use all the standard Fanstatic functionality.

I haven't tried serving images, I'm still quite new to Fanstatic myself, but let me know if that's working, or if there are any problems.

**Comment by mgood** [comment]
I'm going to go ahead and close this since it doesn't look like it requires any special support on the Flask extension side.  If you have trouble let me know and I can try to investigate some more.
