### ISSUE TITLE
Blank lines before doctype

### ISSUE THREAD

**Issue by abulte** [mgood/flask-fanstatic#2]
When I use the recommended way of including assets through fanstatic, I get some blank lines in my HTML before doctype tag, which should be avoided. Is there a way to avoid it?

```
{{ g.fanstatic.needs('js.jquery:jquery') }}
{% extends 'layout.html' %}
```

BTW thanks for this very useful plugin.

**Comment by mgood** [comment]
You can add dashes to the beginning and end of the Jinja expression to tell it to suppress the surrounding whitespace:
http://jinja.pocoo.org/docs/templates/#whitespace-control

I guess I could update the examples to use that.

**Comment by abulte** [comment]
Great, thanks!
